twilio:
  token: ${TWILIO_TOKEN}
  sid: ${TWILIO_SID}

spring:
  cloud:
    gcp:
      project-id: ecstatic-branch-366221
      firestore:
        project-id: ecstatic-branch-366221
        credentials:
          location-file: ${KEYFILE}

phone:
  admin: ${ADMIN_PHONE}
  developer: ${DEVELOPER_PHONE}
  service: ${SERVICE_PHONE}